import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import FrontLayout from "@/shared/layouts/Front";



export const metadata: Metadata = {
  title: "Wong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className="min-h-screen flex flex-col ">
        <ThemeProvider 
          attribute="data-theme"
          // defaultTheme="light"
          // enableSystem={false}
        >
          {children}
            
        </ThemeProvider>  
      </body>
    </html>
  );
}
