import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";


export const metadata: Metadata = {
  title: "Wong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
  {/* class="absolute inset-0 h-full w-full bg-white bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] bg-size-[16px_16px]" */}

      <body className="min-h-full flex flex-col ">
        <ThemeProvider 
          attribute="data-theme"
          // defaultTheme="light"
          // enableSystem={false}
        >
            {children}
        </ThemeProvider>  
      </body>
    </html>
  );
}
